### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ZeweiSong** [GabeAl/NINJA-OPS#15]
Hi, Gabe

I was trying to run NINJA-OPS on my Windows 10 BASH environment. I've got bowtie2 installed in the path and running ok. Here is the error message I got:

Any idea? Thanks!

Running NINJA-OPS filter...
"/mnt/e/Data/SNA_16S/ninja-ops/bin/ninja_filter_linux" "merge.pear.maxee1.fasta" "/mnt/e/Data/SNA_16S/ninja_otu/ninja"   D 1 LOG

Segmentation fault (core dumped)

Traceback (most recent call last):
  File "ninja-ops/bin/ninja.py", line 609, in <module>
    main(p)
  File "ninja-ops/bin/ninja.py", line 566, in main
    logger.log("NINJA-OPS filter time: " + str(t1.timeit(1)))
  File "/usr/lib/python2.7/timeit.py", line 195, in timeit
    timing = self.inner(it, self.timer)
  File "/usr/lib/python2.7/timeit.py", line 100, in inner
    _func()
  File "ninja-ops/bin/ninja.py", line 564, in <lambda>
    run_with_shell=run_with_shell, print_only=args['print_only'])
  File "ninja-ops/bin/ninja.py", line 289, in ninja_filter
    raise ValueError("ERROR: Filtering failed. One possible explanation is a problem with input FASTA formatting. Please rerun with '--check_fasta'. Exiting.")
ValueError: ERROR: Filtering failed. One possible explanation is a problem with input FASTA formatting. Please rerun with '--check_fasta'. Exiting.

**Comment by GabeAl** [comment]
I would strongly recommend using the original Windows version of NINJA-OPS
and the original Windows version of bowtie2 and python instead of using the
Bash environment. ;) This is because I have compiled the ninja_* programs
with a version of GCC greater than the WSL supports (i.e. only up to 4.8).
I could recompile the ninja_filter binary with GCC 4.8 and it should work
fine on WSL as well as normal linux.

But just in case, could you tell me how large the input fasta file is, how
much RAM you have, and whether the same file works on Linux (MSI)?

Thanks for the report! Bear with me as we work through this together. :)

**Comment by swati0689** [comment]
Hello,
 Even I am getting the same error "ERROR: Filtering failed. One possible explanation is a problem with input FASTA formatting. Please rerun with '--check_fasta'. Exiting." How to resolve the same

**Comment by ZeweiSong** [comment]
I got the exact same error when trying to run NINJA-OPS on Windows 10 BASH environment. So to me it is actually not a FASTA format problem.

**Comment by GabeAl** [comment]
Any failure of ninja_filter for any reason will trigger that generic error. NINJA-OPS does not support Windows 10's BASH environment currently. Nor do many bioinformatics tools (try running usearch, uclust, etc -- instant and immediate segfault, not the fault of the programs but W10's bash is not yet complete). 

It's important not to confuse these two issues. The console output does not show any useful information in this case. If you find the time, please post the contents of your log file, @swati0689 , as well as the other information requested in your original report, and we will try to resolve this for you. My hunch in your case is that it is a memory/formatting issue, but I could be wrong and it would take some quick investigating to find out!

@ZeweiSong have you tried the official windows version? The Linux version on the bash environment is not supported, only the native Windows build in the cmd/powershell environment works.

**Comment by GabeAl** [comment]
@ZeweiSong 
Update on this! 

After upgrading my version of Windows 10 to the latest version (Creator's Update, use this: https://go.microsoft.com/fwlink/?linkid=846364) and then updating my BASH Ubuntu environment on Windows to 16.04 like so: https://www.howtogeek.com/278152/how-to-update-the-windows-bash-shell/ 

NINJA-OPS has now started to work on the Windows 10 Bash environment!
