### ISSUE TITLE
NINJA Segmentation error

### ISSUE THREAD

**Issue by swati0689** [GabeAl/NINJA-OPS#16]
I am trying to run NINJA on linux 

I get the following error on using the command

python /home/genetics/Desktop/Ruchi_SRF/NINJA-OPS-master/bin/ninja.py -i /home/genetics/Desktop/Ruchi_SRF/Cases_Controls/combined/combined_seqs.fna -o ninja 

Running NINJA-OPS filter...
"/mnt/e/Data/SNA_16S/ninja-ops/bin/ninja_filter_linux" "merge.pear.maxee1.fasta" "/mnt/e/Data/SNA_16S/ninja_otu/ninja" D 1 LOG

Segmentation fault (core dumped)

Traceback (most recent call last):
File "ninja-ops/bin/ninja.py", line 609, in 
main(p)
File "ninja-ops/bin/ninja.py", line 566, in main
logger.log("NINJA-OPS filter time: " + str(t1.timeit(1)))
File "/usr/lib/python2.7/timeit.py", line 195, in timeit
timing = self.inner(it, self.timer)
File "/usr/lib/python2.7/timeit.py", line 100, in inner
_func()
File "ninja-ops/bin/ninja.py", line 564, in 
run_with_shell=run_with_shell, print_only=args['print_only'])
File "ninja-ops/bin/ninja.py", line 289, in ninja_filter
raise ValueError("ERROR: Filtering failed. One possible explanation is a problem with input FASTA formatting. Please rerun with '--check_fasta'. Exiting.")
ValueError: ERROR: Filtering failed. One possible explanation is a problem with input FASTA formatting. Please rerun with '--check_fasta'. Exiting.
Any idea how to resolve the same

**Comment by GabeAl** [comment]
Hi, thanks for reporting!

A couple of quick questions for you, if that's okay:
1. What version of NINJA are you using? Currently only v1.5.1 and later are
supported, so it's good to use the freshest one.
2. What is the file size of the fasta file you're using? Are the sequences
linear or do the sequences contain line breaks?
3. How much memory (ram) is available on your linux system?

The reason for these questions is that the most common causes of
segmentation problems is either using an old version of NINJA, having
formatting incompatibility in your fasta file, or having insufficient RAM
to run the program on large data.

Thanks!
Gabe
