### ISSUE TITLE
Parsing fails with -F option

### ISSUE THREAD

**Issue by mahermassoud** [GabeAl/NINJA-OPS#21]
Whenever I run NINJA with the -F option, it fails with the following output. All other params work fine.

```
(base) @MAC204241 bin $ python ninja.py -i ~/Desktop/reads/forward.fasta,/Users/massoudmaher/Desktop/reads/reverse.fasta -o ~/Desktop/reads_ninja_F -F
NINJA-OPS v1.5.1
NINJA-OPS database directory is /Users/massoudmaher/Documents/Code/NINJA-OPS/databases/greengenes97
Running NINJA-OPS filter...
"/Users/massoudmaher/Documents/Code/NINJA-OPS/bin/ninja_filter_mac" "/Users/massoudmaher/Desktop/reads/forward.fasta" PE "/Users/massoudmaher/Desktop/reads/reverse.fasta" "/Users/massoudmaher/Desktop/reads_ninja_F/ninja"   D 1 LOG
Using paired-end reads /Users/massoudmaher/Desktop/reads/reverse.fasta
Log writing enabled.
Number of sequences: 60522
Total reads considered: 60522
Reads sorted.
60522 Samples found.
*************************************
*   WARNING!! WARNING!! WARNING!!   *
*   No. of samples = no. of reads   *
*    Casting # of samples to 1.     *
*************************************
Number of reads rejected = 0, committed = 60522
Finished.
NINJA-OPS filter time: 0.344496232
Running Bowtie2...
bowtie2-align-s --no-head -x /Users/massoudmaher/Documents/Code/NINJA-OPS/databases/greengenes97/greengenes97 -S "/Users/massoudmaher/Desktop/reads_ninja_F/alignments.txt" --np 0 --mp "1,1" --rdg "0,1" --rfg "0,1" --score-min "L,0,-0.030000000000000027" --norc -f -1 "/Users/massoudmaher/Desktop/reads_ninja_F/ninja_filt.fa" -2 "/Users/massoudmaher/Desktop/reads_ninja_F/ninja2_filt.fa" --maxins 1400 --no-mixed --no-discordant -p 8 --very-sensitive

Bowtie time: 30.91181909
Running NINJA-OPS compact...
"/Users/massoudmaher/Documents/Code/NINJA-OPS/bin/ninja_compact_mac" "/Users/massoudmaher/Desktop/reads_ninja_F/alignments_uncompacted.txt" "/Users/massoudmaher/Documents/Code/NINJA-OPS/databases/greengenes97/greengenes97.tcf" "/Users/massoudmaher/Desktop/reads_ninja_F/alignments.txt"
Done.
NINJA-OPS compact time: 0.7563568209999971
Running NINJA-OPS parse...
"/Users/massoudmaher/Documents/Code/NINJA-OPS/bin/ninja_parse_filtered_mac" "/Users/massoudmaher/Desktop/reads_ninja_F/ninja" "/Users/massoudmaher/Desktop/reads_ninja_F/alignments.txt" "/Users/massoudmaher/Documents/Code/NINJA-OPS/databases/greengenes97/greengenes97.db" "/Users/massoudmaher/Documents/Code/NINJA-OPS/databases/greengenes97/greengenes97.taxonomy" LOG


Traceback (most recent call last):
  File "ninja.py", line 609, in <module>
    main(p)
  File "ninja.py", line 587, in main
    logger.log("NINJA-OPS parse time: " + str(t3.timeit(1)) + "\n")
  File "/Users/massoudmaher/miniconda3/lib/python3.7/timeit.py", line 176, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "ninja.py", line 585, in <lambda>
    logger, legacy_table, run_with_shell=run_with_shell, print_only=args['print_only'])
  File "ninja.py", line 427, in ninja_parse
    raise ValueError("ERROR: Parsing failed. Exiting.")
ValueError: ERROR: Parsing failed. Exiting.
(base) @MAC204241 bin $
```

**Comment by mahermassoud** [comment]
Also, when this happens, the following output files are empty: ninja_otumap.txt, ninja_filtered.txt. But the rest of the files have content
