### ISSUE TITLE
Memory spike causing crash on dataset of ~250 nt contigs

### ISSUE THREAD

**Issue by pschloss** [GabeAl/NINJA-OPS#7]
I've been trying to play with ninja-ops on some datasets I have and am struggling to get it to work on a dataset of ~250 nt V4 sequences. It seems to die right around 79,010 sequences where it spikes to consuming 58+ gb of RAM. Here's the file I'm using...

https://www.dropbox.com/s/007xusqe3hzx6sx/test.fasta.gz?dl=0

The bowtie executables are in the PATH. Here's the command and output...

```
$ python /home/me/NINJA-OPS-1.3.2/bin/ninja.py -m max -d 2 -i /home/me/test.fasta  -o /home/me/test.ninja
Ninja 1.3.1
Ninja database directory is is/home/pschloss/NINJA-OPS-1.3.2/databases/greengenes97
Running Ninja filter...
"/home/pschloss/NINJA-OPS-1.3.2/bin/ninja_filter_linux" "/home/pschloss/test.fasta" "/home/pschloss/test.ninja/ninja"   D 2
Not using paired-end reads 
Performing NINJA replicon-denoising at 2 compacted reads.
Number of sequences: 79010
Total reads considered: 79010

DONE SORTING. 
79010 Samples found.
Ninja filter time: 0.733674049377
Running Bowtie...
bowtie2-align-s --no-head -x /home/pschloss/NINJA-OPS-1.3.2/databases/greengenes97/greengenes97 -S "/home/pschloss/test.ninja/alignments.txt" --np 0 --mp "1,1" --rdg "0,1" --rfg "0,1" --score-min "L,0,-0.03" --norc -f "/home/pschloss/test.ninja/ninja_filt.fa" -p 4 -k 1 --very-sensitive

Bowtie time: 2.10711193085
Running Ninja parse...
"/home/pschloss/NINJA-OPS-1.3.2/bin/ninja_parse_filtered_linux" "/home/pschloss/test.ninja/ninja" "/home/pschloss/test.ninja/alignments.txt" "/home/pschloss/NINJA-OPS-1.3.2/databases/greengenes97/greengenes97.db" "/home/pschloss/NINJA-OPS-1.3.2/databases/greengenes97/greengenes97.taxonomy"
Opened /home/pschloss/test.ninja/ninja_otutable.biom for OTU Table writing
Total OTUs available: 99322
Number of unique samples: 79010, max reads: 530
couldn't allocate OTU table.

Traceback (most recent call last):
  File "/home/pschloss/NINJA-OPS-1.3.2/bin/ninja.py", line 547, in <module>
    main(p)
  File "/home/pschloss/NINJA-OPS-1.3.2/bin/ninja.py", line 528, in main
    logger.log("Ninja parse time: " + str(t3.timeit(1)) + "\n")
  File "/share/apps/rhel6/python/2.7.9/lib/python2.7/timeit.py", line 195, in timeit
    timing = self.inner(it, self.timer)
  File "/share/apps/rhel6/python/2.7.9/lib/python2.7/timeit.py", line 100, in inner
    _func()
  File "/home/pschloss/NINJA-OPS-1.3.2/bin/ninja.py", line 526, in <lambda>
    logger, legacy_table, run_with_shell=run_with_shell, print_only=args['print_only'])
  File "/home/pschloss/NINJA-OPS-1.3.2/bin/ninja.py", line 374, in ninja_parse
    raise ValueError("ERROR: Parsing failed. Exiting.")
ValueError: ERROR: Parsing failed. Exiting.
```

Changing the `-m` option value doesn't seem to affect things. Suggestions?

**Comment by GabeAl** [comment]
Thanks for the report. This is because NINJA expects the input sequences in a certain format (formats_readme.txt). I agree this is confusing and should work for arbitrary fasta like you suggested by treating it as one sample. To do this I check whether the number of unique sample names (defined by the headers up until an underscore is encountered or the whole thing if not) is equal to the number of sequences. 

The reason I'm not just checking for underscores is that this way preserves the functionality to just name every sequence by its sample without underscores (also supported). 

So try the new v1.3.2!
Also added the option to log each and every sequence and its attendant match where such a match was reported. Enable wth -F in the python wrapper (or LOG in the parser).
